spring:
  profiles:
    active: prod
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    # url: jdbc:mysql://192.168.15.32:3306/data_middleware?characterEncoding=utf8&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false
    # username: root
    # password: akazam@2019
    
#    url: jdbc:mysql://192.168.33.194:3306/MiddlleData?characterEncoding=utf8&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false
    url: jdbc:mysql://192.168.33.194:3306/data_middleware?characterEncoding=utf8&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false
    username: akazam
    password: dbacc355
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池的配置信息
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
  server:
    maxFileSize: 300MB      #上传文件大小限制--单个
    maxRequestSize: 500MB   #上传文件大小限制--总


server:
  port: ${server-port:8080}
  tomcat:
    accesslog:
      enabled: true
      basedir: /logs
      pattern: '%h %l %u %t "%r" %s %b %D'
      prefix: access_log
      directory: /logs/accesslog

akazam:
  excelSavaPath: /home/datamiddleware/sourceExcel   #本地Excel上传到服务器的路径配置，从该路径下读取Excel数据进行导入
  poolSize: 10  #定时导入、导出任务线程池大小
  excelBatchSize: 10000  #Excel批量导入大小

logging:
  file: ./logs/application/datamiddleware.log
  level:
    com.akazam: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %contextName %X{appName} %X{uid} %X{did} %X{traceId} [%thread] %-5level %logger{39}.%M:%line - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %contextName %X{appName} %X{uid} %X{did} %X{traceId} [%thread] %-5level %logger{39}.%M:%line - %msg%n"